### ISSUE TITLE
make query returns an error

### ISSUE THREAD

**Issue by opsinghis** [apollographql/supergraph-demo#11]
I have downloaded the folder and running as prescribed. After running make local, i am running make query and it returns error 

`.scripts/query.sh
{"errors":[{"message":"Couldn't find service with name \"products\"","extensions":{"code":"INTERNAL_SERVER_ERROR","exception":{"stacktrace":["Error: Couldn't find service with name \"products\"","    at executeFetch (/Users/omsingh0/code/supergraph-demo-main/node_modules/@apollo/gateway/dist/executeQueryPlan.js:96:15)","    at executeNode (/Users/omsingh0/code/supergraph-demo-main/node_modules/@apollo/gateway/dist/executeQueryPlan.js:83:23)","    at Object.executeQueryPlan (/Users/omsingh0/code/supergraph-demo-main/node_modules/@apollo/gateway/dist/executeQueryPlan.js:23:33)","    at Object.ApolloGateway.executor (/Users/omsingh0/code/supergraph-demo-main/node_modules/@apollo/gateway/dist/index.js:102:55)","    at processTicksAndRejections (internal/process/task_queues.js:93:5)"]}}}],"data":{"bestSellers":null}}`

**Comment by sgentile** [comment]
I'm also getting this same error

**Comment by prasek** [comment]
@opsinghis @sgentile 👋 thanks for catching this. This was a stale gateway patch version on my end. Bumped to the next patch version and everything was fine. Added ci in #13 to catch this going forward and now using the most recent gateway and server, so should be good to go! 👍
