### ISSUE TITLE
Supergraph readme instructions are causing error

### ISSUE THREAD

**Issue by sevdas** [apollographql/supergraph-demo#136]
I have followed the readme file to test supergraph-demo local demo is working but I get the error below when I try demo managed.

<img width="1211" alt="Screenshot 2021-06-22 at 18 13 17" src="https://user-images.githubusercontent.com/63476393/122970220-87f4a380-d385-11eb-815c-7440c989796c.png"><img width="1211" alt="Screenshot 2021-06-22 at 18 13 17" src="https://user-images.githubusercontent.com/63476393/122970220-87f4a380-d385-11eb-815c-7440c989796c.png">

 First of all, I guess I need to be running services with docker-compose up before I can actually create my federated graph as described on this line:
Create a `Graph` of type `Deployed` with the `Federation` option.

I am using the API key on the federated graph, however, there are no options to change the permissions, but in documentation, if I am in trial mode, I believe that all my API keys will have admin permissions.

I am not sure what I am doing wrong, if the documentation are correct and I am missing a step somewhere or if you need to update the readme file. 

If you can help, that would be great.

**Comment by prasek** [comment]
Hi @sevdas 👋 ... sorry about that, I've pushed a fix ☝️ can you give it a try? 🙏
